config/routes.rb
Rails.application.routes.draw do
 devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}
  get 'search' => 'searches#search'
  namespace :admin do
   resources :categories, only: [:index, :create, :edit, :update]
   resources :items, except: [:destroy]
   resources :orders, only: [:index, :show, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :order_items, only: [:update]
  end
  namespace :admin do
    get 'homes/top'
  end
  devise_for :customers
  namespace :customer do
    resource :customers, only: [:show, :edit, :update]
    get 'customers/exit_check' => 'customers#exit_check'
    patch 'customers/exit' => 'customers#exit'
  end
  scope module: :customer do
    root 'homes#top'
    get 'homes/about' => 'homes#about' 
    get 'orders/check' => 'orders#check'
    get 'orders/thank' => 'orders#thank'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#all_destroy'
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :deliveries, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def fullname
    [last_name, first_name].join
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(20)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :phone_number, :postcode, :address, :email)
  end
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  def index
    @cart_items = current_customer.cart_items
  end
  
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if @cart_item.save
      redirect_to cart_items_path
    else
      render 'index'
    end
  end
  
  def update
    @cart_item = CartItem.find(params[:id])
      if @cart_item.update(cart_item_params)
        redirect_to request.referrer
      else
        render 'index'
      end
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    if @cart_item.destroy
      flash[:alert] = "#{@cart_item.item.name}を削除しました"
      redirect_to request.referrer
    else
      render 'index'
    end
  end
  
  def all_destroy
    current_customer.cart_items.destroy_all
    flash[:alert] = "カートを空にしました"
    redirect_to request.referrer
  end
  
  private
    def cart_item_params
      params.require(:cart_item).permit(:amount, :item_id, :include_blank)
    end
    
    def cart_item_update_params
      params.require(:cart_item).permit(:amount)
    end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  
  def show
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customer_customers_path
    else
      render :edit
    end
  end
  
  def exit
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :phone_number, :postcode, :address, :email)
  end
end

app/controllers/customer/deliveries_controller.rb
class Customer::DeliveriesController < ApplicationController
  before_action :authenticate_customer!

  
  def index
    @delivery = Delivery.new
    @deliveries = current_customer.deliveries
  end

  def create
    @delivery = Delivery.new(delivery_params)
    @delivery.customer_id = current_customer.id
    if @delivery.save
      flash.now[:notice] = "新規配送先を登録しました"
      redirect_to request.referrer || root_path
    else
      render 'index'
    end
  end

  def edit
    @delivery = Delivery.find(params[:id])
  end

  def update
    delivery = Delivery.find(params[:id])
    if delivery.update(delivery_params)
      flash.now[:success] = "配送先を更新しました"
      redirect_to deliveries_path
    else
      render 'edit'
    end
  end
  
  def destroy
    delivery = Delivery.find(params[:id])
    if delivery.destroy
      flash.now[:alert] = "配送先を削除しました"
      redirect_to request.referrer || root_path
    else
      render 'index'
    end
  end
  
  private
  
  def delivery_params
    params.require(:delivery).permit(:postcode, :address, :name)
  end
  
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
     @items = Item.page(params[:page]).reverse_order.per(3)
  end

  def about
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).reverse_order.per(9)
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
  
end

app/controllers/customer/order_items_controller.rb
class Customer::OrderItemsController < ApplicationController
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  
  def new
    @order = Order.new
    @deliveries = current_customer.deliveries
  end
  
  def check
    @cart_items = current_customer.cart_items
    @order = Order.new
    @order.customer_id = current_customer.id
    @order.payment_method = params[:order][:payment_method]
    
    if params[:order][:address_option] == "0" 
      @order.name = current_customer.fullname
      @order.postcode = current_customer.postcode
      @order.address = current_customer.address  
      
    elsif params[:order][:address_option] == "1"  
      @delivery_order = Delivery.find(params[:order][:delivery_id])
      @order.postcode = @delivery_order.postcode  
      @order.address = @delivery_order.address  
      @order.name = @delivery_order.name  
    
    elsif params[:order][:address_option] == "2"  
      @order.postcode = params[:order][:postcode]  
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
    end  
  end
  
  def create
    @order = current_customer.orders.new(order_params)
    @order.customer_id = current_customer.id
    if @order.save
       @cart_items = current_customer.cart_items
         @cart_items.each do |cart_item|
           @order_items = @order.order_items.new
           @order_items.item_id = cart_item.item.id
           @order_items.order_id = @order.id
           @order_items.purchase_price = cart_item.item.excluding_price
           @order_items.ordered_qty = cart_item.amount
           @order_items.save
         end
       @cart_items.destroy_all
       redirect_to '/orders/thank'
    else
      render 'check'
    end
  end
  
  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  
  private
  
  def order_params
    params.require(:order).permit(:postage, :amount_charged, :payment_method, :postcode, :address, :name, :order_status)
  end
  
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_inactive_user, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def reject_inactive_user
    @customer = Customer.find_by(name: params[:customer][:name])
    if @customer
      if @customer.deleted_password?(params[:customer][:password]) && !@customer.is_deleted
        redirect_to new_user_session_path
      end
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customer/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <h2 class="mt-3">会員情報編集</h2>
      <%= form_with model: @customer, url: customer_customers_path, metdod: :patch, local: true do |f| %>
        <table>
          <tr class="form-group">
            <td><%= f.label :"氏名" %></td>
            <td><%= f.text_field :last_name, class: "form-control" %></td>
            <td><%= f.text_field :first_name, class: "form-control" %></td>
          </tr>
          <tr class="form-group">
            <td><%= f.label :"フリガナ" %></td>
            <td><%= f.text_field :kana_last_name, class: "form-control" %></td>
            <td><%= f.text_field :kana_first_name, class: "form-control" %></td>
          </tr>
          <tr class="form-group">
            <td><%= f.label :"郵便番号" %></td>
            <td><%= f.text_field :postcode, class: "form-control" %></td>
          </tr>
          <tr class="form-group">
            <td><%= f.label :"住所" %></td>
            <td><%= f.text_field :address, class: "form-control" %></td>
          </tr>
          <tr class="form-group">
            <td><%= f.label :"電話番号" %></td>
            <td><%= f.text_field :phone_number , class: "form-control" %></td>
          </tr>
          <tr class="form-group">
            <td><%= f.label :"メールアドレス" %></td>
            <td><%= f.text_field :email, class: "form-control" %></td>
          </tr>
        </table>
        <div class="w-50 mx-auto">
          <p class="mt-3">
            <%= f.submit "編集内容を保存", class: "btn btn-success" %>&emsp;
            <%= link_to "退会する", customer_customers_exit_check_path, class: "btn btn-danger" %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customer/customers/exit_check.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto padding:200px;">
      <div class="text-center">
      <h3 class="mt-3 mb-4"><b>本当に退会しますか？</b></h3>
        <p class="mb-1">
          退会すると、会員登録情報や<br>
          これまでの購入履歴が閲覧できなくなります。<br>
          退会する場合は、「退会する」をクリックしてください。</p>
        <div class="mt-4 mb-3">
          <%= link_to "退会しない", customer_customers_path, class: "btn btn-primary" %>&emsp;
          <%= link_to "退会する", customer_customers_exit_path, method: :patch, class: "btn btn-danger" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customer/customers/show.html.erb
<div class="container h-100">
  <div class="row">
    <div class="col-8  mx-auto">
      <h2 class="mb-4 mt-4">マイページ</h2>
      <div class="mb-4">
        <strong>登録情報</strong>&emsp;
        <%= link_to "編集する", edit_customer_customers_path, class: "btn btn-success" %>
      </div>
      <table class="table table-border" border="2" bgcolor="#fff" bordercolor="#BC8F8F">
        <tr>
          <td bgcolor="#FFEFD5">氏名</td>
          <td><%= @customer.last_name %>&emsp;<%= @customer.first_name %></td>
        </tr>
        <tr>
          <td bgcolor="#FFEFD5">カナ</td>
          <td><%= @customer.kana_last_name %>&emsp;<%= @customer.kana_first_name %></td>
        </tr>
        <tr>
          <td bgcolor="#FFEFD5">郵便番号</td>
          <td><%= @customer.postcode %></td>
        </tr>
        <tr>
          <td bgcolor="#FFEFD5">住所</td>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <td bgcolor="#FFEFD5">電話番号</td>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <td bgcolor="#FFEFD5">メールアドレス</td>
          <td><%= @customer.email %></td>
        </tr>
      </table>
      <div class="mt-3 mb-3">
        <strong class="mt-3 mb-3">配送先<span>&emsp;</span></strong>
        <%= link_to "一覧を見る", deliveries_path, class: "btn btn-primary" %>
      </div>
      <div class="mb-3">
        <strong>注文履歴</strong>
        <%= link_to "一覧を見る", orders_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>