config/routes.rb
Rails.application.routes.draw do
 devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}
  get 'search' => 'searches#search'
  namespace :admin do
   resources :categories, only: [:index, :create, :edit, :update]
   resources :items, except: [:destroy]
   resources :orders, only: [:index, :show, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :order_items, only: [:update]
  end
  namespace :admin do
    get 'homes/top'
  end
  devise_for :customers
  namespace :customer do
    resource :customers, only: [:show, :edit, :update]
    get 'customers/exit_check' => 'customers#exit_check'
    patch 'customers/exit' => 'customers#exit'
  end
  scope module: :customer do
    root 'homes#top'
    get 'homes/about' => 'homes#about' 
    get 'orders/check' => 'orders#check'
    get 'orders/thank' => 'orders#thank'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#all_destroy'
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :deliveries, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  
  def fullname
    [last_name, first_name].join
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  
  enum payment_method:{"クレジットカード": 0, "銀行振込": 1}
 # enum order_status: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4}
  enum order_status: {before_payment: 0, payment_check: 1, making: 2, before_delivery: 3, deliveryed: 4}
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(20)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :phone_number, :postcode, :address, :email)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    unless params[:id] == @customer
      @customer = params[:id]
      @orders = Order.where(customer_id: @customer).page(params[:page]).reverse_order.per(10)
    else
      @orders = Order.page(params[:page]).reverse_order.per(10)
    end
  end







  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if params[:order][:order_status] == "payment_check"
      @order.order_items.update_all(production_status: 1)
    end
    redirect_to request.referer
  end
  
  private
  
  def order_params
    params.require(:order).permit(:postage, :amount_charged, :payment_method, :postcode, :address, :name, :order_status)
  end
  
end

app/controllers/customer/cart_items_controller.rb
class Customer::CartItemsController < ApplicationController
  def index
    @cart_items = current_customer.cart_items
  end
  
  def create
    @cart_item = CartItem.new(cart_item_params)
    @cart_item.customer_id = current_customer.id
    if @cart_item.save
      redirect_to cart_items_path
    else
      render 'index'
    end
  end
  
  def update
    @cart_item = CartItem.find(params[:id])
      if @cart_item.update(cart_item_params)
        redirect_to request.referrer
      else
        render 'index'
      end
  end
  
  def destroy
    @cart_item = CartItem.find(params[:id])
    if @cart_item.destroy
      flash[:alert] = "#{@cart_item.item.name}を削除しました"
      redirect_to request.referrer
    else
      render 'index'
    end
  end
  
  def all_destroy
    current_customer.cart_items.destroy_all
    flash[:alert] = "カートを空にしました"
    redirect_to request.referrer
  end
  
  private
    def cart_item_params
      params.require(:cart_item).permit(:amount, :item_id, :include_blank)
    end
    
    def cart_item_update_params
      params.require(:cart_item).permit(:amount)
    end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  
  def show
    @customer = current_customer
  end
  
  def edit
    @customer = current_customer
  end
  
  def update
    @customer = current_customer
    if @customer.update(customer_params)
      redirect_to customer_customers_path
    else
      render :edit
    end
  end
  
  def exit
    @customer = current_customer
    @customer.update(is_deleted: true)
    reset_session
    redirect_to root_path
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :kana_last_name, :kana_first_name, :phone_number, :postcode, :address, :email)
  end
end

app/controllers/customer/deliveries_controller.rb
class Customer::DeliveriesController < ApplicationController
  before_action :authenticate_customer!

  
  def index
    @delivery = Delivery.new
    @deliveries = current_customer.deliveries
  end

  def create
    @delivery = Delivery.new(delivery_params)
    @delivery.customer_id = current_customer.id
    if @delivery.save
      flash.now[:notice] = "新規配送先を登録しました"
      redirect_to request.referrer || root_path
    else
      render 'index'
    end
  end

  def edit
    @delivery = Delivery.find(params[:id])
  end

  def update
    delivery = Delivery.find(params[:id])
    if delivery.update(delivery_params)
      flash.now[:success] = "配送先を更新しました"
      redirect_to deliveries_path
    else
      render 'edit'
    end
  end
  
  def destroy
    delivery = Delivery.find(params[:id])
    if delivery.destroy
      flash.now[:alert] = "配送先を削除しました"
      redirect_to request.referrer || root_path
    else
      render 'index'
    end
  end
  
  private
  
  def delivery_params
    params.require(:delivery).permit(:postcode, :address, :name)
  end
  
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
     @items = Item.page(params[:page]).reverse_order.per(3)
  end

  def about
  end
end

app/controllers/customer/items_controller.rb
class Customer::ItemsController < ApplicationController
  def index
    @items = Item.page(params[:page]).reverse_order.per(9)
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end
  
end

app/controllers/customer/order_items_controller.rb
class Customer::OrderItemsController < ApplicationController
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  
  def new
    @order = Order.new
    @deliveries = current_customer.deliveries
  end
  
  def check
    @cart_items = current_customer.cart_items
    @order = Order.new
    @order.customer_id = current_customer.id
    @order.payment_method = params[:order][:payment_method]
    
    if params[:order][:address_option] == "0" 
      @order.name = current_customer.fullname
      @order.postcode = current_customer.postcode
      @order.address = current_customer.address  
      
    elsif params[:order][:address_option] == "1"  
      @delivery_order = Delivery.find(params[:order][:delivery_id])
      @order.postcode = @delivery_order.postcode  
      @order.address = @delivery_order.address  
      @order.name = @delivery_order.name  
    
    elsif params[:order][:address_option] == "2"  
      @order.postcode = params[:order][:postcode]  
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
    end  
  end
  
  def create
    @order = current_customer.orders.new(order_params)
    @order.customer_id = current_customer.id
    if @order.save
       @cart_items = current_customer.cart_items
         @cart_items.each do |cart_item|
           @order_items = @order.order_items.new
           @order_items.item_id = cart_item.item.id
           @order_items.order_id = @order.id
           @order_items.purchase_price = cart_item.item.excluding_price
           @order_items.ordered_qty = cart_item.amount
           @order_items.save
         end
       @cart_items.destroy_all
       redirect_to '/orders/thank'
    else
      render 'check'
    end
  end
  
  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  
  private
  
  def order_params
    params.require(:order).permit(:postage, :amount_charged, :payment_method, :postcode, :address, :name, :order_status)
  end
  
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_inactive_user, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  def reject_inactive_user
    @customer = Customer.find_by(name: params[:customer][:name])
    if @customer
      if @customer.deleted_password?(params[:customer][:password]) && !@customer.is_deleted
        redirect_to new_user_session_path
      end
    end
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def check
  end

  def thank
  end

  def index
  end

  def show
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/customer/orders/check.html.erb
<div class="container mb-4 h-100">
  <div class="row">
    <div class="col">
      <h2 class="mb-4">注文情報確認</h2>
      <table class="table table-bordered table-light">
        <thead class="bg-dark" style="color:white;">
          <tr>
            <th>商品名</th>
            <th>単価（税込み）</th>
            <th>数量</th>
            <th>小計</th>
          </tr>
        </thead>
        <% sum = 0 %>
        <% @cart_items.each do |cart_item| %>
          <tbody class="font-weight-bold">
            <tr>
              <td><%= attachment_image_tag cart_item.item, :image, size: '80x65', format: 'jpg' %>
              <%= cart_item.item.name %></td>
              <td><%= ((cart_item.item.excluding_price*1.08).round(0)).to_s(:delimited, delimiter: ',') %>円</td>
              <td><%= cart_item.amount %>個</td>
              <td><%= ((cart_item.item.excluding_price*1.08).round(0)*cart_item.amount).to_s(:delimited, delimiter: ',') %>円</td>
            </tr>
          </tbody>
        <% sum += (cart_item.item.excluding_price*1.08).round(0)*cart_item.amount %>
        <% end %>
      </table>
    </div>
  </div>
</div>

<div class="container mb-4">
  <div class="row">
    <div class="col-3">
        <table class="table table-bordered table-light">
            <tbody class="font-weight-bold">
                <tr><td class="bg-dark" style="color:white;">送料</td><td class="table-light"><%= label :postage, 800 %>円</td></tr>
                <tr><td class="bg-dark" style="color:white;">商品代合計</td><td class="table-light"><%= sum.to_s(:delimited, delimiter: ',') %>円</td></tr>
                <tr><td class="bg-dark" style="color:white;">請求金額</td><td class="table-light"><%= label :amount_charged, "#{(sum + 800).to_s(:delimited, delimiter: ',')}" %>円</td></tr>
            </tbody>
        </table>
    </div>
    <div class="col-7 offset-2">
      <table class="mb-4 ml-auto font-weight-bold">
        <tbody>
        <tr><td>お支払い方法</td><td>&emsp;&emsp;<%= @order.payment_method %></td></tr>
        <tr><td>お届け先</td><td>&emsp;&emsp;〒<%= @order.postcode %>&emsp;<%= @order.address %>&emsp;<%= @order.name %></td></tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="mx-auto" style="width: 150px;">
      <div>
        <%= form_with model: @order, url: orders_path, local: true do |f| %>
        <%= f.hidden_field :postage, :value => 800 %>
        <%= f.hidden_field :amount_charged, :value => "#{sum + 800}" %>
        <%= f.hidden_field :payment_method, :value => @order.payment_method %>
        <%= f.hidden_field :postcode, :value => @order.postcode %>
        <%= f.hidden_field :address, :value => @order.address %>
        <%= f.hidden_field :name, :value => @order.name %>
        <%= f.hidden_field :order_status, :value => @order.order_status %>
        <%= f.submit "注文を確定する", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
 </div>
</div>

app/views/customer/orders/index.html.erb
<div class="container mb-4">
  <div class="row">
    <div class="col">
      <h2 class="mb-4">注文履歴一覧</h2>
      <table class="table table-bordered table-light font-weight-bold">
        <thead class="bg-dark" style="color:white;">
          <tr>
            <th>注文日</th>
            <th>配送先</th>
            <th>注文商品</th>
            <th>支払金額</th>
            <th>ステータス</th>
            <th>注文詳細</th>
          </tr>
        </thead>
        
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td><%= order.created_at.strftime('%Y/%m/%d') %></td>
            <td>
              〒<%= order.postcode %><br>
              <%= order.address %><br>
              <%= order.name %>
            </td>
            <td>
            <% order.order_items.each do |order_item| %>
            <%= order_item.item.name %><br>
            <% end %>
            </td>
            <td><%= (order.amount_charged).to_s(:delimited, delimiter: ',') %>円</td>
            <td style="color:red;"><%= order.order_status_i18n %></td>
            <td><%= link_to "表示する", order_path(order.id) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/customer/orders/new.html.erb
<div class="container mb-4">
  <div class="row">
    <div class="col">
      <div class="w-50 mx-auto">
        <h2 class="mb-4">注文情報入力</h2>
          <%= form_with model: @order, url: orders_check_path, local: true, method: :get do |f| %>
          <div class="form-group">
            <%= f.label :payment_method, "支払い方法", class: "font-weight-bold" %><br>
            <%= f.radio_button :payment_method, "クレジットカード" %>
            <span>クレジットカード</span><br>
            <%= f.radio_button :payment_method, "銀行振込" %>
            <span>銀行振込</span><br>
          </div>
          <div class="form-group">
            <%= f.label :address, "お届け先", class: "font-weight-bold" %><br>
            <%= f.radio_button :address_option, 0, checked: true %>
            <span>ご自身の住所</span><br>
            <span>〒<%= current_customer.postcode %><%= current_customer.address %></span><br>
                    <%= current_customer.fullname %><br>
          </div>
          <div class="form-group">
            <% unless @deliveries == [] %>
            <%= f.radio_button :address_option, 1 %>
            <span>登録済み住所から選択</span><br>
            <%= f.collection_select :delivery_id, @deliveries, :id, :order_address %><br>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.radio_button :address_option, 2 %>
            <span>新しい登録先</span><br>
            <%= f.label :postcode, "郵便番号（ハイフンなし）" %><br>
            <%= f.text_field :postcode, class: "form-control w-50" %><br>
            <%= f.label :address, "住所" %><br>
            <%= f.text_field :address, class: "form-control" %><br>
            <%= f.label :name, "宛名" %><br>
            <%= f.text_field :name, class: "form-control w-50" %><br>
          </div>
            <%= f.submit '確認画面へ', class: "btn btn-success"  %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customer/orders/show.html.erb
<div class="container">
<h1>注文履歴詳細</h1>
<div class="row font-weight-bold">
<div class="col-sm-8">
<p>注文情報</p>
<table class="table table-bordered table-light" style="width:600px;">
    <tr><td class="bg-dark" style="width:150px; color:white;">注文日</td><td><%= @order.created_at.strftime("%Y/%m/%d") %></td></tr>
    <tr><td class="bg-dark" style="width:150px; color:white;">配送先</td><td>〒<%= @order.postcode %><br><%= @order.address %><br><%= @order.name %></td></tr>
    <tr><td class="bg-dark" style="width:150px; color:white;">支払方法</td><td><%= @order.payment_method %></td></tr>
    <tr><td class="bg-dark" style="width:150px; color:white;">ステータス</td><td style="color:red;"><%= @order.order_status_i18n %></td></tr>
</table>
</div>
<div class="col-sm-4">
<p>請求情報</p>
<table class="table table-bordered table-light" style="width:300px;">
    <tr><td class="bg-dark" style="color:white;">商品合計</td><td><%= (@order.amount_charged - @order.postage).to_s(:delimited, delimiter: ',') %>円</td></tr>
    <tr><td class="bg-dark" style="color:white;">配送料</td><td><%= @order.postage %>円</td></tr>
    <tr><td class="bg-dark" style="color:white;">ご請求金額</td><td><%= (@order.amount_charged).to_s(:delimited, delimiter: ',') %>円</td></tr>
</table>
</div>
</div>


<p style="font-weight: bold;">注文内容</p>
<table class="table table-borderedt table-light font-weight-bold" style="width:800px;">
    <thead>
        <th class="bg-dark" style="color:white;">商品</th>
        <th class="bg-dark" style="color:white;">単価（税込）</th>
        <th class="bg-dark" style="color:white;">個数</th>
        <th class="bg-dark" style="color:white;">小計</th>
    </thead>
    <tbody>
        <% @order_items.each do |order_item| %>
        <tr>
            <td><%= order_item.item.name %></td><td><%= ((order_item.purchase_price * 1.08).round(0)).to_s(:delimited, delimiter: ',') %>円</td><td><%= order_item.ordered_qty %>個</td><td><%= ((order_item.purchase_price * 1.08).round(0) * order_item.ordered_qty).to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <% end %>
    </tbody>
</table>
</div>

app/views/customer/orders/thank.html.erb
<script src="./assets/javascripts/jquery.min.js"></script>
<h2 class="text-center" id="title" style="padding:200px; font-size:50px; color:red;">ご注文ありがとうございました！！！</h2>