config/routes.rb
Rails.application.routes.draw do
 devise_for :admins, controllers: {
  sessions: 'admins/sessions'
}
  get 'search' => 'searches#search'
  namespace :admin do
   resources :categories, only: [:index, :create, :edit, :update]
   resources :items, except: [:destroy]
   resources :orders, only: [:index, :show, :update]
   resources :customers, only: [:index, :show, :edit, :update]
   resources :order_items, only: [:update]
  end
  namespace :admin do
    get 'homes/top'
  end
  devise_for :customers
  namespace :customer do
    resource :customers, only: [:show, :edit, :update]
    get 'customers/exit_check' => 'customers#exit_check'
    patch 'customers/exit' => 'customers#exit'
  end
  scope module: :customer do
    root 'homes#top'
    get 'homes/about' => 'homes#about' 
    get 'orders/check' => 'orders#check'
    get 'orders/thank' => 'orders#thank'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    delete 'cart_items' => 'cart_items#all_destroy'
    resources :deliveries, only: [:index, :create, :destroy, :edit, :update]
    resources :items, only: [:index, :show]
    resources :orders, only: [:new, :create, :index, :show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items, dependent: :destroy
  
  enum payment_method:{"クレジットカード": 0, "銀行振込": 1}
 # enum order_status: {"入金待ち": 0, "入金確認": 1, "製作中": 2, "発送準備中": 3, "発送済み": 4}
  enum order_status: {before_payment: 0, payment_check: 1, making: 2, before_delivery: 3, deliveryed: 4}
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    unless params[:id] == @customer
      @customer = params[:id]
      @orders = Order.where(customer_id: @customer).page(params[:page]).reverse_order.per(10)
    else
      @orders = Order.page(params[:page]).reverse_order.per(10)
    end
  end







  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if params[:order][:order_status] == "payment_check"
      @order.order_items.update_all(production_status: 1)
    end
    redirect_to request.referer
  end
  
  private
  
  def order_params
    params.require(:order).permit(:postage, :amount_charged, :payment_method, :postcode, :address, :name, :order_status)
  end
  
end

app/controllers/customer/orders_controller.rb
class Customer::OrdersController < ApplicationController
  before_action :authenticate_customer!
  
  def new
    @order = Order.new
    @deliveries = current_customer.deliveries
  end
  
  def check
    @cart_items = current_customer.cart_items
    @order = Order.new
    @order.customer_id = current_customer.id
    @order.payment_method = params[:order][:payment_method]
    
    if params[:order][:address_option] == "0" 
      @order.name = current_customer.fullname
      @order.postcode = current_customer.postcode
      @order.address = current_customer.address  
      
    elsif params[:order][:address_option] == "1"  
      @delivery_order = Delivery.find(params[:order][:delivery_id])
      @order.postcode = @delivery_order.postcode  
      @order.address = @delivery_order.address  
      @order.name = @delivery_order.name  
    
    elsif params[:order][:address_option] == "2"  
      @order.postcode = params[:order][:postcode]  
      @order.address = params[:order][:address]
      @order.name = params[:order][:name]
    end  
  end
  
  def create
    @order = current_customer.orders.new(order_params)
    @order.customer_id = current_customer.id
    if @order.save
       @cart_items = current_customer.cart_items
         @cart_items.each do |cart_item|
           @order_items = @order.order_items.new
           @order_items.item_id = cart_item.item.id
           @order_items.order_id = @order.id
           @order_items.purchase_price = cart_item.item.excluding_price
           @order_items.ordered_qty = cart_item.amount
           @order_items.save
         end
       @cart_items.destroy_all
       redirect_to '/orders/thank'
    else
      render 'check'
    end
  end
  
  def index
    @orders = current_customer.orders
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.order_items
  end

  
  private
  
  def order_params
    params.require(:order).permit(:postage, :amount_charged, :payment_method, :postcode, :address, :name, :order_status)
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
  end

  def check
  end

  def thank
  end

  def index
  end

  def show
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container mb-4 h-100">
  <div class="row">
    <div class="col">
      <h2 class="mb-4">注文履歴一覧</h2>
      <table class="table table-bordered table-light font-weight-bold">
        <thead class="bg-dark" style="color:white;">
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
          <tbody>
            <% @orders.each do |order| %>
              <tr>
                <td>
                  <%= link_to admin_order_path(order) do %>
                  <%= order.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
                  <% end %>
                </td>
                <td><%= order.customer.fullname %></td>
                <td>
                  <% sum = 0 %> 
                  <% order.order_items.each do |order_item| %>
                  <% sum += order_item.ordered_qty %>
                  <% end %>
                  <%= sum %>
                </td>
                <td><%= order.order_status_i18n %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
      <%= paginate @orders %>

    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<h2>注文履歴詳細</h2>

<table>
  <tr>
    <th>購入者</th>
    <td>
      <%= link_to admin_customer_path(@order.customer) do %>
      <%= @order.customer.last_name %><span>&emsp;</span><%= @order.customer.first_name %>
      <% end %>
    </td>
  </tr>
  <tr>
    <th>注文日</th>
    <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
  </tr>
  <tr>
    <th>配送先</th>
    <td>〒<%= @order.postcode %><span>&emsp;</span><%= @order.address %></td>
  </tr>
  <tr>
    <td><%= @order.name %></td>
  </tr>
  <tr>
    <th>支払い方法</th>
    <td><%= @order.payment_method %></td>
  </tr>
  <tr>
　　<th>注文ステータス</th>
　　<td>
　　  <%= form_with model: @order, url: admin_order_path(@order), method: :patch, local: true do |f| %>
　　  　<%= f.select :order_status, Order.order_statuses_i18n.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
　　  　<%= f.submit "変更" %>
　　  <% end %>
　　</td>
  </tr>
</table>
<% sum = 0 %>
<% @order_items.each do |order_item| %>
<table>
  <tr>
    <th>商品名</th>
    <th>単価（税込）</th>
    <th>数量</th>
    <th>小計</th>
    <th>制作ステータス</th>
  </tr>
  <tr>
    <td><%= order_item.item.name %></td>
    <td><%= (order_item.item.excluding_price*1.08).floor %></td>
    <td><%= order_item.ordered_qty %></td>
    <td><%= ((order_item.item.excluding_price*1.08)*(order_item.ordered_qty)).floor %></td>
    <td>
      <%= form_with model: order_item, url: admin_order_item_path(order_id: @order.id, id: order_item.id), method: :patch, local: true do |f| %>
        <%= f.select :production_status, OrderItem.production_statuses.keys.map {|k| [I18n.t("enums.order_item.production_status.#{k}"), k]} %>
        <%= f.submit "変更" %>
      <% end %>
    </td>
  </tr>
</table>
<% sum += (order_item.item.excluding_price)*(order_item.ordered_qty) %>
<% end %>



<table>
  <tr>
    <th>商品合計</th>
    <td><%= (sum*1.08).floor %></td>
  </tr>
  <tr>
    <th>送料</th>
    <td><%= @order.postage %></td>
  </tr>
  <tr>
    <th>請求金額合計</th>
　　<td><%= @order.amount_charged %></td>
  </tr>
</table>